puzzle/puzzletime

- app/views/employee_master_data/_attrs.html.haml
> Fix variable name (emergency contact)

- config/locales/models.de-DE.yml
de_DE translation (based on de_CH)
```
--- models.de-CH.yml	2019-02-19 16:36:07.953359978 +0100
+++ models.de-DE.yml	2019-02-19 16:45:30.541734070 +0100
@@ -11,2 +11,2 @@
-        one: Absenzart
-        other: Absenzarten
+        one: Abwesenheitsart
+        other: Abwesenheitsarten
@@ -14,2 +14,2 @@
-        one: Absenz
-        other: Absenzen
+        one: Abwesenheit
+        other: Abwesenheiten
@@ -129,2 +129,2 @@
-        offered_hours: Offerierte Stunden
-        offered_rate: Offerierter Stundensatz
+        offered_hours: Angebotene Stunden
+        offered_rate: Angebotener Stundensatz
@@ -132 +132 @@
-        report_type: Report Typ
+        report_type: Report-Typ
@@ -141 +141 @@
-        street: Strasse
+        street: Straße
@@ -192 +192 @@
-        street: Strasse
+ …
```
> New models de_DE (based on de_CH)

- test/helpers/employee_master_data_helper_test.rb
This just adds a missing test for #62
> Add format_year_of_service test

- app/helpers/accounting_posts_helper.rb
- app/views/accounting_posts/_form.html.haml
Disable restriction checkboxes after blocking bookings have been made on a
position.
> Restrict accounting_post restrictions

- app/domain/order/cockpit/accounting_post_row.rb
- app/models/planning.rb
- app/views/accounting_posts/_cockpit_table.html.haml
- test/domain/order/cockpit_test.rb
This changes the accounting positions view according to our internal ticket 49288.
> Accounting positions cockpit changes

- .github/workflows/rails-tests.yaml
- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- test/helpers/format_helper_test.rb
- test/support/crud_test_helper.rb
PR to test new github actions for test. Please don't merge yet!
> Add github action for rails tests

- .rubocop_todo.yml
- app/assets/javascripts/application.js.coffee
- app/assets/javascripts/meal_compensations.js.coffee
- app/assets/javascripts/modules/work_item_autocomplete.js.coffee
- app/assets/stylesheets/_icons.scss
- app/assets/stylesheets/_worktimes.scss
- app/controllers/accounting_posts_controller.rb
- app/controllers/meal_compensations_controller.rb
- app/controllers/order_services_controller.rb
- app/controllers/ordertimes_controller.rb
- app/helpers/meal_compensations_helper.rb
- app/helpers/order_services_helper.rb
- app/models/ability.rb
- app/models/employee.rb
- app/models/worktime.rb
- app/views/accounting_posts/_form.html.haml
- app/views/layouts/_menu.html.haml
- app/views/meal_compensations/_date_filter.html.haml
- app/views/meal_compensations/_list.html.haml
- app/views/meal_compensations/index.html.haml
- app/views/meal_compensations/index.js.haml
- app/views/order_services/_value_filters.html.haml
- app/views/ordertimes/_form.html.haml
- app/views/shared/_submenu_employees.html.haml
- app/views/work_items/search.json.jbuilder
- app/views/worktimes/_worktime.html.haml
- config/locales/models.de-CH.yml
- config/locales/models.de-DE.yml
- config/routes.rb
- db/migrate/20200228100244_add_meal_compensation.rb
Implementation of the new meal compensation feature
> Meal compensation

- app/views/meal_compensations/_list.html.haml
- app/views/meal_compensations/_positions.html.haml
- app/views/meal_compensations/_worktimes.html.haml
- app/views/meal_compensations/details.html.haml
- app/views/meal_compensations/index.html.haml
- app/views/meal_compensations/show.html.haml
- app/views/order_services/_value_filters.html.haml
- app/views/ordertimes/_form.html.haml
- app/views/shared/_submenu_employees.html.haml
- config/locales/models.de-CH.yml
- config/locales/models.de-DE.yml
> meal_compensation: fix wording

- config/application.rb
> Fix environment startup in case the db does not exist yet

- .github/workflows/code-style-review.yaml
- .github/workflows/rails-tests.yaml
This Pull Request updates all GitHub Actions workflows. The following changes were made:
* Format `.yaml`
* Use official `ruby/setup-ruby@v1` consitently
* Use official `reviewdog/action*`
> CI: Update Workflows

- app/serializers/api/v1/employee_serializer.rb
- doc/development/01_setup.md
Add city and birthday attribute to employee_serializer and fix a couple small mistakes in the setup.md file.
> Feature BBT-737 Update employee api

- config/locales/models.de-DE.yml
minor change in de-DE language file
> correct spelling mistake in de-DE language file

- app/assets/javascripts/application.js.coffee
- app/controllers/concerns/filterable.rb
- app/controllers/invoices_controller.rb
- app/controllers/order_services_controller.rb
- app/domain/order/services/csv_filename_generator.rb
- app/views/order_services/_actions.html.haml
- app/views/order_services/_filters.html.haml
- app/views/order_services/_value_filters.html.haml
- app/views/worktimes_report/_report_config.html.haml
- app/views/worktimes_report/_report_header.html.haml
- test/integration/invoice_form_test.rb
Enables the selection of multiple positions in the tab 'order_services'. This selection is also propagated to the creation of an invoice and the creation of a time rapport.
> selection of multiple positions (63116)

- test/controllers/order_reports_controller_test.rb
- test/domain/order/report_test.rb
- test/integration/order_reports_test.rb
Add new tests and edit existing ones to test workings of OrderReports
> Tests - order controlling tab reorganization (63114 )

- app/assets/javascripts/application.js.coffee
- app/helpers/navigation_helper.rb
- app/views/order_services/_actions.html.haml
- bin/rubocop-changed
- bin/rubocop-staged
There are still some short visual bugs (selectize input fields with multiple options flicker sometimes)
> fix turbolink / selectize bug that leads to duplicate input field rendering (63994)

- app/assets/javascripts/application.js.coffee
- app/assets/javascripts/cockpit.js.coffee
- app/assets/stylesheets/_orders.scss
- app/controllers/accounting_posts_controller.rb
- app/domain/order/cockpit.rb
- app/domain/order/cockpit/accounting_post_row.rb
- app/domain/order/cockpit/total_row.rb
- app/views/accounting_posts/_cockpit_header.html.haml
- app/views/accounting_posts/_cockpit_table.html.haml
- app/views/accounting_posts/index.html.haml
- test/domain/order/cockpit_test.rb
- test/integration/create_order_test.rb
adds a filter to the tab "accounting posts" for an order
> make accounting posts filterable (63950)

- .rubocop.yml
- app/assets/javascripts/application.js.coffee
- app/assets/javascripts/reports_invoices.js.coffee
- app/controllers/invoice_reports_controller.rb
- app/domain/invoice/report.rb
- app/domain/invoice/report/entry.rb
- app/domain/invoice/report/total.rb
- app/domain/order/report.rb
- app/helpers/filter_helper.rb
- app/helpers/sort_helper.rb
- app/models/ability.rb
- app/models/invoice.rb
- app/views/invoice_reports/_actions.html.haml
- app/views/invoice_reports/_filters.html.haml
- app/views/invoice_reports/_list.html.haml
- app/views/invoice_reports/_submenu.html.haml
- app/views/invoice_reports/index.html.haml
- app/views/invoice_reports/index.js.haml
- app/views/orders/_submenu.html.haml
- config/routes.rb
- test/domain/invoice/report_test.rb
- test/domain/order/report_test.rb
- test/helpers/table_helper_test.rb
Add Tab for invoices-controlling, where all invoices can be listed / filtered
> Add invoices controlling (63987 )

- app/views/invoice_reports/_list.html.haml
There was an error in the invoice controlling where the permissions for syncing with the invoicing instance was checked. This was fixed
> fix bug related to invoicing instance (64179)

- app/assets/stylesheets/components/_selectize.scss
This doesn't fix the selectize / turbolinks bug but it at least makes it less ugly
> hide elements which are  uninitialized by selectize (64181)

- app/assets/javascripts/datepicker.js.coffee
This should also fix the issues with selectize on  browser-back.
@Kagemaru I'd be really happy for a review here, as I am no expert in Js/coffeescript and might not 100% understand all the implications of the used code / possible side-effects etc.
> only selectively destroy and re-add selectize & datepicker elements (64305)
